### ISSUE TITLE
OpenStreetMap license

### ISSUE THREAD

**Issue by lucadelu** [jplusplus/rsf-index-2015#37]
Hi,

I just notice that the OpenStreetMap license is missing on the web map. For more info read [here](http://www.openstreetmap.org/copyright)

You can add it close the link to Leaflet

**Comment by Pirhoo** [comment]
Hi @lucadelu,

that's my fault, I forgot to add the attribution option when I configured the map's tiles. Will be in the next release. Thanks for the heads-up!

**Comment by lucadelu** [comment]
Hi @Pirhoo,
thanks a lot for the quick fix.
